# Generated by Django 4.1.7 on 2023-05-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('pagina_web', models.URLField()),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_barras', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_caducidad', models.DateField()),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, upload_to='productos/')),
                ('marca', models.CharField(max_length=50)),
                ('presentacion', models.CharField(max_length=50)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ubicacion', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('unidades', models.CharField(max_length=50)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.proveedor')),
            ],
        ),
    ]
