# Generated by Django 4.1.7 on 2023-05-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('analgesicos', 'Analgésicos'), ('antibioticos', 'Antibióticos'), ('antiinflamatorios', 'Antiinflamatorios'), ('antidepresivos', 'Antidepresivos'), ('antialergicos', 'Antialérgicos'), ('antidiabeticos', 'Antidiabéticos'), ('antihistaminicos', 'Antihistamínicos'), ('anticoagulantes', 'Anticoagulantes'), ('anticonvulsivantes', 'Anticonvulsivantes'), ('antiespasmodicos', 'Antiespasmódicos'), ('antipireticos', 'Antipiréticos'), ('antitusivos', 'Antitusivos'), ('broncodilatadores', 'Broncodilatadores'), ('cardiotonicos', 'Cardiotónicos'), ('descongestionantes', 'Descongestionantes'), ('diureticos', 'Diuréticos'), ('hipnoticos', 'Hipnóticos y sedantes'), ('hormonas', 'Hormonas'), ('analgesicos', 'Inhibidores de la bomba de protones'), ('laxantes', 'Laxantes'), ('relajantes', 'Relajantes musculares'), ('vitaminas', 'Vitaminas y suplementos')], max_length=70),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(choices=[('pfizer', 'Pfizer'), ('bayer', 'Bayer'), ('roche', 'Roche'), ('novartis', 'Novartis'), ('merck', 'Merck'), ('sanofi', 'Sanofi'), ('glaxosmithkline', 'GlaxoSmithKline'), ('johnsonjohnson', 'Johnson & Johnson'), ('abbott', 'Abbott'), ('eli lilly', 'Eli Lilly'), ('astrazeneca', 'AstraZeneca'), ('bristolmyerssquibb', 'Bristol-Myers Squibb'), ('teva', 'Teva'), ('sandoz', 'Sandoz'), ('mylan', 'Mylan'), ('abbvie', 'AbbVie'), ('amgen', 'Amgen'), ('biogen', 'Biogen'), ('celgene', 'Celgene'), ('gilead', 'Gilead'), ('merckkgaa', 'Merck KGaA'), ('allergan', 'Allergan'), ('shionogi', 'Shionogi'), ('takeda', 'Takeda'), ('baxter', 'Baxter'), ('merckco', 'Merck & Co.'), ('bectondickinson', 'Becton, Dickinson and Company'), ('daiichi sankyo', 'Daiichi Sankyo'), ('gliead sciences', 'Gilead Sciences'), ('grifols', 'Grifols'), ('hikma', 'Hikma'), ('lupin', 'Lupin'), ('mallinckrodt', 'Mallinckrodt'), ('myriad genetics', 'Myriad Genetics'), ('pernod ricard', 'Pernod Ricard'), ('pfenex', 'Pfenex'), ('pharmacia', 'Pharmacia'), ('pliva', 'Pliva'), ('ptc therapeutics', 'PTC Therapeutics'), ('ra pharma', 'Ra Pharma'), ('santhera pharmaceuticals', 'Santhera Pharmaceuticals'), ('sarepta therapeutics', 'Sarepta Therapeutics'), ('sun pharmaceutical', 'Sun Pharmaceutical'), ('taiho oncology', 'Taiho Oncology'), ('tesaro', 'Tesaro'), ('thermo fisher scientific', 'Thermo Fisher Scientific'), ('tolero pharmaceuticals', 'Tolero Pharmaceuticals'), ('xoma', 'Xoma'), ('zoetis', 'Zoetis'), ('zydus cadila', 'Zydus Cadila')], max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(choices=[('ampolla', 'Ampolla'), ('tableta', 'Tableta'), ('cápsula', 'Cápsula'), ('solución', 'Solución'), ('jarabe', 'Jarabe'), ('crema', 'Crema'), ('pomada', 'Pomada'), ('gel', 'Gel'), ('spray', 'Spray'), ('gotas', 'Gotas'), ('supositorio', 'Supositorio'), ('polvo', 'Polvo'), ('inyección', 'Inyección'), ('ovulo', 'Óvulo'), ('granulado', 'Granulado'), ('líquido', 'Líquido'), ('capsula blanda', 'Cápsula blanda'), ('comprimido', 'Comprimido'), ('efervescente', 'Efervescente'), ('suspensión', 'Suspensión'), ('enema', 'Enema'), ('parche', 'Parche'), ('espuma', 'Espuma'), ('línea nasal', 'Línea nasal'), ('chicle', 'Chicle'), ('spray nasal', 'Spray nasal'), ('polvo inhalado', 'Polvo inhalado'), ('tableta masticable', 'Tableta masticable'), ('tableta bucal', 'Tableta bucal'), ('polvo efervescente', 'Polvo efervescente'), ('polvo oral', 'Polvo oral'), ('solución oral', 'Solución oral'), ('suspensión oral', 'Suspensión oral'), ('inyección subcutánea', 'Inyección subcutánea'), ('inyección intramuscular', 'Inyección intramuscular'), ('inyección intravenosa', 'Inyección intravenosa'), ('inyección intravenosa lenta', 'Inyección intravenosa lenta'), ('inyección intravenosa en bolo', 'Inyección intravenosa en bolo'), ('inyección intraarterial', 'Inyección intraarterial'), ('inyección intracardiaca', 'Inyección intracardiaca'), ('inyección intradérmica', 'Inyección intradérmica'), ('inyección intraarticular', 'Inyección intraarticular'), ('implante', 'Implante'), ('cápsula oral de liberación prolongada', 'Cápsula oral de liberación prolongada'), ('tableta de liberación prolongada', 'Tableta de liberación prolongada'), ('tableta recubierta', 'Tableta recubierta'), ('gránulos para suspensión oral', 'Gránulos para suspensión oral'), ('crema vaginal', 'Crema vaginal'), ('gel vaginal', 'Gel vaginal'), ('óvulo vaginal', 'Óvulo vaginal'), ('solución inyectable', 'Solución inyectable'), ('solución para nebulizar', 'Solución para nebulizar'), ('solución oftálmica', 'Solución oftálmica'), ('crema para la piel', 'Crema para la piel'), ('solución auricular', 'Solución auricular'), ('aerosol', 'Aerosolo')], max_length=100),
        ),
    ]
