# Generated by Django 4.1.7 on 2023-05-18 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_categoria_alter_producto_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_adicional', models.DecimalField(decimal_places=2, max_digits=5)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('id_vendedor', models.IntegerField()),
                ('id_factura', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.venta')),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(through='producto.VentaProducto', to='producto.producto'),
        ),
    ]
