# Generated by Django 4.1.7 on 2023-05-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'ciudades'},
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre Completo'),
        ),
    ]
